// Fetch the SOS brand webfonts (the families index.html loads from Google
// Fonts) and vendor them locally as woff2 + a self-contained @font-face
// stylesheet, so the design bundle renders on-brand inside claude.ai/design's
// CSP sandbox (no remote font hosts). Families/weights mirror index.html.
// Run: node .design-sync/fetch-fonts.mjs   (see NOTES.md)
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const OUT = new URL('./fonts/', import.meta.url).pathname;
mkdirSync(OUT, { recursive: true });

// One CSS2 request per family (keeps filenames stable + subsets minimal).
const FAMILIES = [
  'Fraunces:ital,opsz,wght@1,9..144,900',
  'Syne:wght@400;600;700;800',
  'DM+Sans:ital,wght@0,300;0,400;0,500;1,400',
  'DM+Mono:wght@400;500',
  'JetBrains+Mono:wght@400;500;600',
  'Archivo+Black',
  'Inter:wght@400;500;600;700;800',
  'Gochi+Hand',
  'Noto+Sans+JP:wght@300;400',
];

const curl = (url) => execFileSync('curl', ['-sSL', '-A', UA, url], { maxBuffer: 64 * 1024 * 1024 });
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

let out = '/* SOS brand webfonts — vendored from Google Fonts (latin subset).\n   Generated by .design-sync/fetch-fonts.mjs. */\n';
let count = 0;

for (const fam of FAMILIES) {
  const css = curl(`https://fonts.googleapis.com/css2?family=${fam}&display=swap`).toString('utf8');
  // Keep only the /* latin */ blocks — the DS UI is latin; JP kept for Noto.
  const wantJP = fam.startsWith('Noto');
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  for (const [, subset, block] of blocks) {
    if (subset !== 'latin' && !(wantJP && subset === 'japanese')) continue;
    const famName = /font-family:\s*'([^']+)'/.exec(block)?.[1] || 'font';
    const weight = /font-weight:\s*([^;]+);/.exec(block)?.[1]?.trim() || '400';
    const style = /font-style:\s*([^;]+);/.exec(block)?.[1]?.trim() || 'normal';
    const urlM = /url\((https:\/\/[^)]+\.woff2)\)(\s*format\([^)]*\))?/.exec(block);
    if (!urlM) continue;
    const fname = `${slug(famName)}-${weight.replace(/\s+/g, '_')}-${style}${subset === 'japanese' ? '-jp' : ''}.woff2`;
    writeFileSync(join(OUT, fname), curl(urlM[1]));
    out += block.replace(urlM[0], `url(./${fname}) format('woff2')`).replace(/\s+/g, ' ').trim() + '\n';
    count++;
  }
}

writeFileSync(join(OUT, 'fonts.css'), out);
console.log(`vendored ${count} woff2 faces → .design-sync/fonts/`);
